### ISSUE TITLE
Error code 10

### ISSUE THREAD

**Issue by GorlikItsMe** [deadlinecode/dll-inject#2]
When I try use injectPID function return 10. I found this in code https://github.com/h110m/dll-inject/blob/main/functions.cc#L212 and propably this is place where that 10 is set, but I dont understand what is wrong.

**Comment by h110m** [comment]
Can you please provide a code snippet of how you tried to use the injectPID function.
It looks like you set the second argument in the function to a wrong value as far as i know.
So if you are using injectPID you have to use it like this

```js
injector.injectPID(1234, 'mydll.dll')
```

This means the first argument has to be of type number and has to be the proccess id.
The second argument has to be of type string and should be the relative path to the dll file you are trying to inject.
Also please try to run your programm with enough permissions because from os to os it is diffrent and you maybe have to give your programm enough permissions to inject something

**Comment by h110m** [comment]
@GorlikItsMe 
It's been a week so im closing the issue. 
Feel free to reopen if there is anything new on this topic.
